POST http://localhost:5000/api/startTask
Content-Type: application/json

{
"taskName":  "run_job",
"taskLogId":  "xxx1"
}

###

POST http://localhost:5000/api/startTask
Content-Type: application/json

{
"taskName":  "run_job_2",
"taskLogId":  "xxx2"
}

###